/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppQuestionnaireRouteImport } from './routes/_authenticated/app/questionnaire'
import { Route as AuthenticatedAppPoliciesRouteImport } from './routes/_authenticated/app/policies'
import { Route as AuthenticatedAppCompareRouteImport } from './routes/_authenticated/app/compare'
import { Route as AuthenticatedAppThreadIdRouteImport } from './routes/_authenticated/app/$threadId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppQuestionnaireRoute =
  AuthenticatedAppQuestionnaireRouteImport.update({
    id: '/app/questionnaire',
    path: '/app/questionnaire',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppPoliciesRoute =
  AuthenticatedAppPoliciesRouteImport.update({
    id: '/app/policies',
    path: '/app/policies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCompareRoute = AuthenticatedAppCompareRouteImport.update({
  id: '/app/compare',
  path: '/app/compare',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppThreadIdRoute =
  AuthenticatedAppThreadIdRouteImport.update({
    id: '/app/$threadId',
    path: '/app/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/$threadId': typeof AuthenticatedAppThreadIdRoute
  '/app/compare': typeof AuthenticatedAppCompareRoute
  '/app/policies': typeof AuthenticatedAppPoliciesRoute
  '/app/questionnaire': typeof AuthenticatedAppQuestionnaireRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/$threadId': typeof AuthenticatedAppThreadIdRoute
  '/app/compare': typeof AuthenticatedAppCompareRoute
  '/app/policies': typeof AuthenticatedAppPoliciesRoute
  '/app/questionnaire': typeof AuthenticatedAppQuestionnaireRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/app/$threadId': typeof AuthenticatedAppThreadIdRoute
  '/_authenticated/app/compare': typeof AuthenticatedAppCompareRoute
  '/_authenticated/app/policies': typeof AuthenticatedAppPoliciesRoute
  '/_authenticated/app/questionnaire': typeof AuthenticatedAppQuestionnaireRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/app/$threadId'
    | '/app/compare'
    | '/app/policies'
    | '/app/questionnaire'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/$threadId'
    | '/app/compare'
    | '/app/policies'
    | '/app/questionnaire'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/app/$threadId'
    | '/_authenticated/app/compare'
    | '/_authenticated/app/policies'
    | '/_authenticated/app/questionnaire'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/questionnaire': {
      id: '/_authenticated/app/questionnaire'
      path: '/app/questionnaire'
      fullPath: '/app/questionnaire'
      preLoaderRoute: typeof AuthenticatedAppQuestionnaireRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/policies': {
      id: '/_authenticated/app/policies'
      path: '/app/policies'
      fullPath: '/app/policies'
      preLoaderRoute: typeof AuthenticatedAppPoliciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/compare': {
      id: '/_authenticated/app/compare'
      path: '/app/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AuthenticatedAppCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/$threadId': {
      id: '/_authenticated/app/$threadId'
      path: '/app/$threadId'
      fullPath: '/app/$threadId'
      preLoaderRoute: typeof AuthenticatedAppThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppThreadIdRoute: typeof AuthenticatedAppThreadIdRoute
  AuthenticatedAppCompareRoute: typeof AuthenticatedAppCompareRoute
  AuthenticatedAppPoliciesRoute: typeof AuthenticatedAppPoliciesRoute
  AuthenticatedAppQuestionnaireRoute: typeof AuthenticatedAppQuestionnaireRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppThreadIdRoute: AuthenticatedAppThreadIdRoute,
  AuthenticatedAppCompareRoute: AuthenticatedAppCompareRoute,
  AuthenticatedAppPoliciesRoute: AuthenticatedAppPoliciesRoute,
  AuthenticatedAppQuestionnaireRoute: AuthenticatedAppQuestionnaireRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
